#!/bin/sh


function errors () {
	/bin/echo
}

function trapexit () {
	errors
	trap "" 0  
	exit 0
}

trap trapexit 0 1 2 3 15



IPERF_OPTS="-c 169.254.1.2 -t 60 -f M -i 2 -l 32K" 

while sleep 1; do 
	/bin/echo -en "\n------ Single -- ${IPERF_OPTS}----\n"
	iperf ${IPERF_OPTS} 2>&1 | egrep 'MBytes/sec' 
	sleep 1
	/bin/echo -en "\n------ Dual ----- ${IPERF_OPTS}---\n"
	iperf ${IPERF_OPTS} -d 2>&1 | egrep 'MBytes/sec' 
done

